version: '3.8'
services:
  db:
    image: 'mysql/mysql-server:latest'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=geoquest
      - MYSQL_USER=geoquest
      - MYSQL_PASSWORD=geoquest
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  mongo:
    image: mongo:latest
    restart: always
    container_name: geoquest-backend
    hostname: localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: geoquest
      MONGO_INITDB_ROOT_PASSWORD: geoquest
    ports:
      - "27017:27017"