definitions:
  domain.QuestDTO:
    properties:
      name:
        type: string
    type: object
  domain.UserDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  handler.CouponRequest:
    properties:
      description:
        type: string
      expiration_day:
        type: integer
      expiration_hour:
        type: integer
      expiration_month:
        type: integer
      expiration_year:
        type: integer
    type: object
  handler.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: App designed to communicate with GeoQuest's mobile app and provide
    CRUD functions
  title: GeoQuest Backend
  version: "1.0"
paths:
  /quests/:
    get:
      consumes:
      - application/json
      description: Quest info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.QuestDTO'
        "500":
          description: Internal Server Error
      summary: Quests
      tags:
      - Quests
    post:
      consumes:
      - application/json
      description: Save new quest
      parameters:
      - description: Quest to save
        in: body
        name: quest
        required: true
        schema:
          $ref: '#/definitions/domain.QuestDTO'
      - description: Auth token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: New quest
      tags:
      - Quests
  /quests/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a quest
      parameters:
      - description: Quest ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Quests
      tags:
      - Quests
    get:
      consumes:
      - application/json
      description: Quest info
      parameters:
      - description: Quest ID
        in: path
        name: id
        required: true
        type: string
      - description: Auth token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.QuestDTO'
        "500":
          description: Internal Server Error
      summary: Quests
      tags:
      - Quests
    put:
      consumes:
      - application/json
      description: Quest info
      parameters:
      - description: Quest to update
        in: body
        name: quest
        required: true
        schema:
          $ref: '#/definitions/domain.QuestDTO'
      - description: Quest ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Quests
      tags:
      - Quests
  /users/:
    post:
      consumes:
      - application/json
      description: Save new user
      parameters:
      - description: User to save
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: New user
      tags:
      - Users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: User info
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UserDTO'
        "500":
          description: Internal Server Error
      summary: User
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: User to update
        in: body
        name: quest
        required: true
        schema:
          $ref: '#/definitions/domain.UserDTO'
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: User
      tags:
      - Users
  /users/{id}/coupons:
    get:
      consumes:
      - application/json
      description: Coupon
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Coupon
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Save new coupon
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Coupon to save
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.CouponRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: New coupon
      tags:
      - Users
  /users/sessions:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: User to log in
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Login user
      tags:
      - Users
swagger: "2.0"
